notifications:
  slack: zewo:VjyVCCQvTOw9yrbzQysZezD1
language: generic
matrix:
  include:
    - os: osx
      env: JOB=SwiftPM_OSX
      osx_image: xcode11
    - os: linux
      env: JOB=SwiftPM_linux
      dist: trusty
      sudo: required
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build -c release
  - swift build
  - swift test
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       eval "$(curl -sL https://raw.githubusercontent.com/lgaches/swifttravisci/master/codecov)";
     fi'
